### ISSUE TITLE
adding more configuration options(enhancement)

### ISSUE THREAD

**Issue by Silentassassin9** [CAPS123987/Better-Nuclear-Generator#1]
After adding the plugin to my server, some of my players were wondering if the cap of 4 uranium at a time could removed/adjusted
and adding this as a configuration option to adjust maybe between some reasonable values  for example 1-20 could be a really nice upgrade for server owners

Along side this, some of my players know about the earlier explosion size of the reactor meltdowns and wanted to see if they could be added back
This being added in a configuration options being true or false for the larger explosion could also be a new facet to tie with the new caps of fuel/coolant being added with larger fuel values at the time of meltdown affecting explosion size

**Comment by CAPS123987** [comment]
thank you for the idea, I will add option for more uran but be aware that when you put more uran you need more coolant. I'm sorry but I don't understand the second part, explosions were always the same size, now it just doesn't explode when block is broken

**Comment by CAPS123987** [comment]
![image](https://github.com/CAPS123987/Better-Nuclear-Generator/assets/87692752/40eb6b72-fbf3-4174-abd4-ac9b3f8e100c)
bigger explosion? :D
