### ISSUE TITLE
reactor explosion results tps 12

### ISSUE THREAD

**Issue by RIPISDRAD** [CAPS123987/Better-Nuclear-Generator#16]
## Description (Required)
reactor exploded and everywhere 5chunk of each side goes with radioactive particles (i think is the main reason of it)
everywhere is green

reproduce :
explode the reactor by over hitting

## Expected behavior (Required)
to dont f the server up :/
i dont care about the damage or anything else but 2 things 
i dont know its not my server but im sure its ur latest sf addon

**Comment by CAPS123987** [comment]
I apologize for any inconvenience caused, but the functionality is operating as expected. In the configuration file, there are two options available to reduce the severity of explosions: *largeExplosionFallout* and *biggerExplosion*. You can disable these options if needed.

If I understand correctly, as the server owner, you are responsible for configuring the plugins installed on the server.

**Comment by RIPISDRAD** [comment]
hi again can't u make config of how low the particles would be and it would
be great cause i love the explosion just not the tps which im kinda sure is
25 chunks full of particles and gl in ur exams hope u reach your dreams
btw um not the owner/developer or anything just a stupid fool as i think
for now but a crazy one🤔
