### ISSUE TITLE
generator blows up even with too much coolant

### ISSUE THREAD

**Issue by Boomer-1** [CAPS123987/Better-Nuclear-Generator#7]
## Description (Required)
started up the generator, set coolant to 6 cells per 8t, 1 uranium per 1200 t
in about 30 seconds it over heated and blew up

## Expected behavior (Required)
shouldn't blow up with too much coolant. my guess is there's an error in the formula causing it to go too low then it begins to increase rapidly

## Server Log / Error Report
no errors

## Environment (Required)

 - Minecraft Version: 1.20.1
 - CS-CoreLib Version:
 - Slimefun Version: 1143
 - Plugin Version:  11

**Comment by CAPS123987** [comment]
resolved here https://blob.build/project/Better-Nuclear-Reactor
