### ISSUE TITLE
reactor coolant and uranium appear to disappear when added via the reactor input

### ISSUE THREAD

**Issue by Boomer-1** [CAPS123987/Better-Nuclear-Generator#9]
## Description (Required)
build the generator
add 3 stacks of coolant cells in the reactor input. the first 2 stacks don't appear in the reactor. while the gen will continue running it shows none in the machine once the first stack is gone. same happens with uranium

## Expected behavior (Required)
to see exactly what's in the machine interface, same as the core sf nuclear reactor

## Server Log / Error Report
none

## Environment (Required)

 - Minecraft Version: 1.20.1
 - CS-CoreLib Version:
 - Slimefun Version: 1143
 - Plugin Version: 11

**Comment by CAPS123987** [comment]
This is intended, the reactor stores some coolant in it self, 128 coolant and 64 uranium, you can see percentage in the menu, also I'll look in all of issues that you created in few days currently I can't.
